services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: reminders
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

  app:
    image: ghcr.io/only-hell/catty-final-v2:lab4-clean
    restart: always
    ports:
      - "8080:8181"
    environment:
      - DATABASE_URL=mysql://user:password@db:3306/reminders
    depends_on:
      - db

volumes:
  db_data:
