name: CD Pipeline
on:
  push:
    branches: [ "lab3" ]
  release:
    types: [published, created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: course.prafdin.ru
          port: 2288
          username: vboxuser
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Переменные
            IMAGE="ghcr.io/${{ github.repository_owner }}/catty-reminders-app:${{ github.sha }}"
            
            echo "🔐 Logging in to GHCR..."
            echo "${{ secrets.PAT_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            echo "📦 Pulling and starting..."
            docker pull $IMAGE
            docker rm -f lab3-app 2>/dev/null || true
            sudo fuser -k 8181/tcp 2>/dev/null || true
            
            docker run -d --name lab3-app --restart always -p 8181:8181 -e DEPLOY_REF=${{ github.sha }} $IMAGE
            
            echo "✅ Nuclear Deploy Finished"