name: Deploy

on:
  push:
    branches: [ lab4-clean ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy app
        run: |
          cd ~/catty-reminders-app
          bash deploy.sh lab4-clean
