name: CD Pipeline
on:
  push:
    branches: [ "lab3*" ]
  release:
    types: [published, created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: course.prafdin.ru
          port: 2288
          username: vboxuser
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/vboxuser/catty-reminders-app
            git config --global --add safe.directory /home/vboxuser/catty-reminders-app
            # Выкачиваем конкретный коммит, чтобы не было ошибки оторванной головы
            git fetch origin ${{ github.sha }}
            git checkout -f ${{ github.sha }}
            chmod +x deploy.sh
            ./deploy.sh ${{ github.sha }}